### ISSUE TITLE
pytorch_lightning.callbacks update

### ISSUE THREAD

**Issue by Inamul-Hassan** [HHousen/TransformerSum#79] opened 2023-03-02 09:36 UTC
In helper.py update the pytorch_lightning.callbacks.base.Callback to pytorch_lightning.callbacks.Callback

**Comment by HHousen** [comment] 2023-04-16 03:53
Technically a duplicate of #78. The solution is to downgrade pytorch-lightning to v1.6.5 by running `pip install pytorch-lightning==1.6.5`. See #78 for more details.

**Closed by HHousen** 2023-04-16 03:53 UTC
